/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        char result = (char)0;
        HashMap<Character, Integer> map = new HashMap<>();
        for(char c : s.toCharArray() )
        {
            if(map.containsKey(c))
                map.put(c, map.get(c)+1 );
            else
                map.put(c,1);
        }
           
        for(char c : t.toCharArray() )
        {
            if(map.containsKey(c) )
            {
                int count = map.get(c);
                if(count == 0)
                    result = c;
                else
                    map.put(c, count-1);
            }
            else
                result = c;
        }
        return result;
    }
}
